"""v0.75 — generate MCP_SERVERS.md index from per-MCP plugin manifests.

Walks `plugin/coscientist-*-mcp/.claude-plugin/plugin.json` + the
companion `.mcp.json` to build a sorted markdown table of every
custom MCP server in this repo.

Pure stdlib. Mirrors `lib/skill_index.py` (v0.67).
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class McpEntry:
    name: str
    description: str
    version: str
    server_name: str  # the key under mcpServers in .mcp.json
    tools: tuple[str, ...]
    keywords: tuple[str, ...]
    plugin_path: Path


_TOOL_DECL = re.compile(r"^def (\w+)\(", re.MULTILINE)


def _extract_tools(server_py: Path) -> tuple[str, ...]:
    """Pull every top-level `def <name>(` defined just after `@mcp.tool()`.

    Naive but sufficient: the FastMCP convention places `@mcp.tool()`
    on the line directly preceding the function definition.
    """
    if not server_py.exists():
        return ()
    text = server_py.read_text()
    out: list[str] = []
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if "@mcp.tool()" in line:
            # Look ahead for the next `def name(`.
            for j in range(i + 1, min(i + 6, len(lines))):
                m = re.match(r"\s*def (\w+)\(", lines[j])
                if m:
                    out.append(m.group(1))
                    break
    return tuple(out)


def discover_mcps(plugins_root: Path) -> list[McpEntry]:
    """Return one McpEntry per MCP plugin (suffix `-mcp`), sorted by name."""
    entries: list[McpEntry] = []
    for pj in sorted(plugins_root.glob("coscientist-*-mcp/.claude-plugin/plugin.json")):
        plugin_dir = pj.parent.parent
        manifest = json.loads(pj.read_text())
        mcp_json_path = plugin_dir / ".mcp.json"
        server_name = ""
        if mcp_json_path.exists():
            mcp_cfg = json.loads(mcp_json_path.read_text())
            servers = mcp_cfg.get("mcpServers") or {}
            if servers:
                server_name = next(iter(servers))
        server_py = plugin_dir / "server" / "server.py"
        tools = _extract_tools(server_py)
        entries.append(McpEntry(
            name=manifest.get("name", plugin_dir.name),
            description=manifest.get("description", ""),
            version=manifest.get("version", ""),
            server_name=server_name,
            tools=tools,
            keywords=tuple(manifest.get("keywords", [])),
            plugin_path=plugin_dir,
        ))
    entries.sort(key=lambda e: e.name)
    return entries


_HEADER = """# MCP servers index

Custom Model Context Protocol servers shipped by Coscientist.
Auto-generated by `lib/mcp_index.py`. Regenerate with:

```bash
uv run python -m lib.mcp_index > MCP_SERVERS.md
```

A test (`tests/test_mcp_index.py`) asserts this file matches the
generator output, so a stale `MCP_SERVERS.md` will fail CI.

## Install

```bash
/plugin marketplace add epireve/coscientist
/plugin install <plugin-name>@coscientist
```

## Servers

| # | Plugin | Server name | Version | Tools |
|---|---|---|---|---|
"""


def render_index(entries: list[McpEntry]) -> str:
    lines = [_HEADER.rstrip("\n")]
    for i, e in enumerate(entries, 1):
        tools_blob = ", ".join(f"`{t}`" for t in e.tools) if e.tools else "—"
        lines.append(
            f"| {i} | `{e.name}` | `{e.server_name}` | "
            f"{e.version} | {tools_blob} |"
        )
    lines.append("")
    lines.append("## Per-server detail")
    lines.append("")
    for e in entries:
        lines.append(f"### `{e.name}` ({e.version})")
        lines.append("")
        # Strip pipes + collapse whitespace for paragraph rendering.
        desc = e.description.replace("\n", " ").strip()
        lines.append(desc)
        lines.append("")
        lines.append(f"- **Server name** (in MCP host): `{e.server_name}`")
        lines.append(f"- **Plugin path**: `{e.plugin_path.relative_to(_repo_root())}`")
        if e.tools:
            lines.append(f"- **Tools**: {', '.join('`' + t + '`' for t in e.tools)}")
        if e.keywords:
            lines.append(f"- **Keywords**: {', '.join('`' + k + '`' for k in e.keywords)}")
        lines.append("")
    lines.append(f"**Total servers**: {len(entries)}")
    lines.append("")
    return "\n".join(lines)


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def main(argv: list[str] | None = None) -> int:
    plugins_root = _repo_root() / "plugin"
    entries = discover_mcps(plugins_root)
    print(render_index(entries), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
