"""v0.67 — generate SKILLS.md index from per-skill frontmatter.

Walks `.claude/skills/*/SKILL.md`, parses YAML frontmatter (name +
description + when_to_use), emits a sorted markdown index. Pure
stdlib (line-based YAML; no pyyaml dep).
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class SkillEntry:
    name: str
    description: str
    when_to_use: str
    path: Path


_FRONT_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)


def _parse_frontmatter(text: str) -> dict[str, str]:
    """Naive line-based YAML parser sufficient for our 3-key shape.

    Handles: simple `key: value` pairs, ignores nested mappings.
    Multi-line values not supported (none of our SKILL.md files use them).
    """
    m = _FRONT_RE.match(text)
    if not m:
        return {}
    body = m.group(1)
    out: dict[str, str] = {}
    for line in body.splitlines():
        m2 = re.match(r"^([a-zA-Z_][a-zA-Z0-9_]*):\s*(.*)$", line)
        if m2:
            out[m2.group(1)] = m2.group(2).strip()
    return out


def discover_skills(skills_root: Path) -> list[SkillEntry]:
    """Return one SkillEntry per .claude/skills/<dir>/SKILL.md, sorted by name."""
    entries: list[SkillEntry] = []
    for skill_md in sorted(skills_root.glob("*/SKILL.md")):
        text = skill_md.read_text()
        fm = _parse_frontmatter(text)
        name = fm.get("name") or skill_md.parent.name
        entries.append(SkillEntry(
            name=name,
            description=fm.get("description", ""),
            when_to_use=fm.get("when_to_use", ""),
            path=skill_md,
        ))
    entries.sort(key=lambda e: e.name)
    return entries


_HEADER = """# Skills index

Auto-generated by `lib/skill_index.py`. Regenerate with:

```bash
uv run python -m lib.skill_index > SKILLS.md
```

A test (`tests/test_skill_index.py`) asserts this file matches
the generator output, so a stale `SKILLS.md` will fail CI.

| # | Skill | Description |
|---|---|---|
"""


def render_index(entries: list[SkillEntry]) -> str:
    """Render entries as a markdown table. Deterministic — same input
    always yields byte-identical output."""
    lines = [_HEADER.rstrip("\n")]
    for i, e in enumerate(entries, 1):
        # Markdown table cells: collapse whitespace and escape pipes.
        desc = e.description.replace("\n", " ").replace("|", "\\|").strip()
        # Cap description for readability.
        if len(desc) > 240:
            desc = desc[:237].rstrip() + "..."
        lines.append(f"| {i} | `{e.name}` | {desc} |")
    lines.append("")  # trailing newline
    lines.append(f"**Total skills**: {len(entries)}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    repo_root = Path(__file__).resolve().parents[1]
    skills_root = repo_root / ".claude" / "skills"
    entries = discover_skills(skills_root)
    print(render_index(entries), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
